[phases.setup]
nixPkgs = [
    "tesseract",
    "tesseract-data-eng",
    "tesseract-data-vie",
    "ghostscript",
    "unpaper",
    "pngquant"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"
